{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.shusek",
    "module": "kmedia-bridge-api",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-metadata-0.2.0.jar",
          "url": "kmedia-bridge-api-0.2.0.jar",
          "size": 6704,
          "sha512": "7f7028ef4317bb060405ec4ddc169c03b12b35029ba5a07891161c881369c31ef4b2d5242e02880713275d0f7078670ef9ffe11078c679a14dcdb0ca6994653b",
          "sha256": "13bba81c7b2cc9bee6e6c0ff9879e1a3c095ec7d3457328a36cd441eb6a3ffe2",
          "sha1": "b10154bcaef032e561aa5f0d0ad372dcbdbcab73",
          "md5": "f14c3cc135c53efe778ed5d296d8c749"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "api-kotlin-0.2.0-sources.jar",
          "url": "kmedia-bridge-api-0.2.0-sources.jar",
          "size": 3992,
          "sha512": "530501b265594bdc79ab3001505879f574b5f88d1251c56f51b529853419b27a8fcb0a9ba44ec72b3ade33a3f820e2f1ed18ad6c6e9bd0e2f5fdee8756f313e3",
          "sha256": "37dc5909d9cab42d9ee8ce058a29533fa32ad5f9afea2112e9a4b75f17d0cdd5",
          "sha1": "65c83861fc0928ff36db1f11daf43e3ef160c47a",
          "md5": "d812297bc13b5e1982cc2bfe5f739e12"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmedia-bridge-api-android/0.2.0/kmedia-bridge-api-android-0.2.0.module",
        "group": "io.github.shusek",
        "module": "kmedia-bridge-api-android",
        "version": "0.2.0"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmedia-bridge-api-android/0.2.0/kmedia-bridge-api-android-0.2.0.module",
        "group": "io.github.shusek",
        "module": "kmedia-bridge-api-android",
        "version": "0.2.0"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmedia-bridge-api-android/0.2.0/kmedia-bridge-api-android-0.2.0.module",
        "group": "io.github.shusek",
        "module": "kmedia-bridge-api-android",
        "version": "0.2.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmedia-bridge-api-iosarm64/0.2.0/kmedia-bridge-api-iosarm64-0.2.0.module",
        "group": "io.github.shusek",
        "module": "kmedia-bridge-api-iosarm64",
        "version": "0.2.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmedia-bridge-api-iosarm64/0.2.0/kmedia-bridge-api-iosarm64-0.2.0.module",
        "group": "io.github.shusek",
        "module": "kmedia-bridge-api-iosarm64",
        "version": "0.2.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmedia-bridge-api-iosarm64/0.2.0/kmedia-bridge-api-iosarm64-0.2.0.module",
        "group": "io.github.shusek",
        "module": "kmedia-bridge-api-iosarm64",
        "version": "0.2.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmedia-bridge-api-iossimulatorarm64/0.2.0/kmedia-bridge-api-iossimulatorarm64-0.2.0.module",
        "group": "io.github.shusek",
        "module": "kmedia-bridge-api-iossimulatorarm64",
        "version": "0.2.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmedia-bridge-api-iossimulatorarm64/0.2.0/kmedia-bridge-api-iossimulatorarm64-0.2.0.module",
        "group": "io.github.shusek",
        "module": "kmedia-bridge-api-iossimulatorarm64",
        "version": "0.2.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmedia-bridge-api-iossimulatorarm64/0.2.0/kmedia-bridge-api-iossimulatorarm64-0.2.0.module",
        "group": "io.github.shusek",
        "module": "kmedia-bridge-api-iossimulatorarm64",
        "version": "0.2.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmedia-bridge-api-jvm/0.2.0/kmedia-bridge-api-jvm-0.2.0.module",
        "group": "io.github.shusek",
        "module": "kmedia-bridge-api-jvm",
        "version": "0.2.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmedia-bridge-api-jvm/0.2.0/kmedia-bridge-api-jvm-0.2.0.module",
        "group": "io.github.shusek",
        "module": "kmedia-bridge-api-jvm",
        "version": "0.2.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmedia-bridge-api-jvm/0.2.0/kmedia-bridge-api-jvm-0.2.0.module",
        "group": "io.github.shusek",
        "module": "kmedia-bridge-api-jvm",
        "version": "0.2.0"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmedia-bridge-api-linuxarm64/0.2.0/kmedia-bridge-api-linuxarm64-0.2.0.module",
        "group": "io.github.shusek",
        "module": "kmedia-bridge-api-linuxarm64",
        "version": "0.2.0"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmedia-bridge-api-linuxarm64/0.2.0/kmedia-bridge-api-linuxarm64-0.2.0.module",
        "group": "io.github.shusek",
        "module": "kmedia-bridge-api-linuxarm64",
        "version": "0.2.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmedia-bridge-api-linuxx64/0.2.0/kmedia-bridge-api-linuxx64-0.2.0.module",
        "group": "io.github.shusek",
        "module": "kmedia-bridge-api-linuxx64",
        "version": "0.2.0"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmedia-bridge-api-linuxx64/0.2.0/kmedia-bridge-api-linuxx64-0.2.0.module",
        "group": "io.github.shusek",
        "module": "kmedia-bridge-api-linuxx64",
        "version": "0.2.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmedia-bridge-api-macosarm64/0.2.0/kmedia-bridge-api-macosarm64-0.2.0.module",
        "group": "io.github.shusek",
        "module": "kmedia-bridge-api-macosarm64",
        "version": "0.2.0"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmedia-bridge-api-macosarm64/0.2.0/kmedia-bridge-api-macosarm64-0.2.0.module",
        "group": "io.github.shusek",
        "module": "kmedia-bridge-api-macosarm64",
        "version": "0.2.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmedia-bridge-api-macosarm64/0.2.0/kmedia-bridge-api-macosarm64-0.2.0.module",
        "group": "io.github.shusek",
        "module": "kmedia-bridge-api-macosarm64",
        "version": "0.2.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmedia-bridge-api-macosx64/0.2.0/kmedia-bridge-api-macosx64-0.2.0.module",
        "group": "io.github.shusek",
        "module": "kmedia-bridge-api-macosx64",
        "version": "0.2.0"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmedia-bridge-api-macosx64/0.2.0/kmedia-bridge-api-macosx64-0.2.0.module",
        "group": "io.github.shusek",
        "module": "kmedia-bridge-api-macosx64",
        "version": "0.2.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmedia-bridge-api-macosx64/0.2.0/kmedia-bridge-api-macosx64-0.2.0.module",
        "group": "io.github.shusek",
        "module": "kmedia-bridge-api-macosx64",
        "version": "0.2.0"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmedia-bridge-api-mingwx64/0.2.0/kmedia-bridge-api-mingwx64-0.2.0.module",
        "group": "io.github.shusek",
        "module": "kmedia-bridge-api-mingwx64",
        "version": "0.2.0"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmedia-bridge-api-mingwx64/0.2.0/kmedia-bridge-api-mingwx64-0.2.0.module",
        "group": "io.github.shusek",
        "module": "kmedia-bridge-api-mingwx64",
        "version": "0.2.0"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kmedia-bridge-api-wasm-js/0.2.0/kmedia-bridge-api-wasm-js-0.2.0.module",
        "group": "io.github.shusek",
        "module": "kmedia-bridge-api-wasm-js",
        "version": "0.2.0"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kmedia-bridge-api-wasm-js/0.2.0/kmedia-bridge-api-wasm-js-0.2.0.module",
        "group": "io.github.shusek",
        "module": "kmedia-bridge-api-wasm-js",
        "version": "0.2.0"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kmedia-bridge-api-wasm-js/0.2.0/kmedia-bridge-api-wasm-js-0.2.0.module",
        "group": "io.github.shusek",
        "module": "kmedia-bridge-api-wasm-js",
        "version": "0.2.0"
      }
    }
  ]
}
