{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmedia-bridge-api/0.2.0/kmedia-bridge-api-0.2.0.module",
    "group": "io.github.shusek",
    "module": "kmedia-bridge-api",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-mingwX64Main-0.2.0.klib",
          "url": "kmedia-bridge-api-mingwx64-0.2.0.klib",
          "size": 43119,
          "sha512": "788a9d21f4334cd1eacc62a033d4e6e02180b44da088dc109c37e69065ece6ff67087e11a11a2681eb56427d9a634d7815aedd00de1b013a86a12cb21a6e92a9",
          "sha256": "b977ff5569b19a1ffc9f88dd7f8ec44300d7168ef6e3549686a1d165a9d4b967",
          "sha1": "d4b4507aec5e3e6c09d979ff1aa4666636b77afc",
          "md5": "8ab7e4f0bcc65bcb430026afd98a7b44"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "api-mingwx64-0.2.0-sources.jar",
          "url": "kmedia-bridge-api-mingwx64-0.2.0-sources.jar",
          "size": 3992,
          "sha512": "530501b265594bdc79ab3001505879f574b5f88d1251c56f51b529853419b27a8fcb0a9ba44ec72b3ade33a3f820e2f1ed18ad6c6e9bd0e2f5fdee8756f313e3",
          "sha256": "37dc5909d9cab42d9ee8ce058a29533fa32ad5f9afea2112e9a4b75f17d0cdd5",
          "sha1": "65c83861fc0928ff36db1f11daf43e3ef160c47a",
          "md5": "d812297bc13b5e1982cc2bfe5f739e12"
        }
      ]
    }
  ]
}
