{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmedia-bridge-api/0.2.0/kmedia-bridge-api-0.2.0.module",
    "group": "io.github.shusek",
    "module": "kmedia-bridge-api",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "api.aar",
          "url": "kmedia-bridge-api-android-0.2.0.aar",
          "size": 59939,
          "sha512": "123030ce095d3db22d652df032210010295ce579523e5d007703c54e69fd9d1d5755cfe4e1d5839a593adde54e74d7c402f967c06e6da24b76568e0d63e041d7",
          "sha256": "daf9f323147f7619e76dee5599f854c26a125e011c03791601b211c8fb271e8d",
          "sha1": "4edd176e13a9e5ae64868e9b80187edc216e9381",
          "md5": "e966f6b0be463c9c0552cfe4fbc8518c"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "api.aar",
          "url": "kmedia-bridge-api-android-0.2.0.aar",
          "size": 59939,
          "sha512": "123030ce095d3db22d652df032210010295ce579523e5d007703c54e69fd9d1d5755cfe4e1d5839a593adde54e74d7c402f967c06e6da24b76568e0d63e041d7",
          "sha256": "daf9f323147f7619e76dee5599f854c26a125e011c03791601b211c8fb271e8d",
          "sha1": "4edd176e13a9e5ae64868e9b80187edc216e9381",
          "md5": "e966f6b0be463c9c0552cfe4fbc8518c"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "api-android-0.2.0-sources.jar",
          "url": "kmedia-bridge-api-android-0.2.0-sources.jar",
          "size": 3992,
          "sha512": "530501b265594bdc79ab3001505879f574b5f88d1251c56f51b529853419b27a8fcb0a9ba44ec72b3ade33a3f820e2f1ed18ad6c6e9bd0e2f5fdee8756f313e3",
          "sha256": "37dc5909d9cab42d9ee8ce058a29533fa32ad5f9afea2112e9a4b75f17d0cdd5",
          "sha1": "65c83861fc0928ff36db1f11daf43e3ef160c47a",
          "md5": "d812297bc13b5e1982cc2bfe5f739e12"
        }
      ]
    }
  ]
}
