{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmedia-bridge-api/0.3.0/kmedia-bridge-api-0.3.0.module",
    "group": "io.github.shusek",
    "module": "kmedia-bridge-api",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "api.aar",
          "url": "kmedia-bridge-api-android-0.3.0.aar",
          "size": 69270,
          "sha512": "07b81a0a636df2114b375a1b58dc119d03601153e2214201d48f7c968348f4fcca894b2b6e17aef53a7d98d69243a43d6f279d2b164c0a7cb4ecd1e3a769d1dd",
          "sha256": "be90c21b945d4671b5f41a7db9daea9c19241c420695589413f61754bf1e6595",
          "sha1": "fc9e0a94375873952d8c1cbd460e6e3c8830e87c",
          "md5": "b5093cb44afbc4074ed42e3c26c038ea"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "api.aar",
          "url": "kmedia-bridge-api-android-0.3.0.aar",
          "size": 69270,
          "sha512": "07b81a0a636df2114b375a1b58dc119d03601153e2214201d48f7c968348f4fcca894b2b6e17aef53a7d98d69243a43d6f279d2b164c0a7cb4ecd1e3a769d1dd",
          "sha256": "be90c21b945d4671b5f41a7db9daea9c19241c420695589413f61754bf1e6595",
          "sha1": "fc9e0a94375873952d8c1cbd460e6e3c8830e87c",
          "md5": "b5093cb44afbc4074ed42e3c26c038ea"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "api-android-0.3.0-sources.jar",
          "url": "kmedia-bridge-api-android-0.3.0-sources.jar",
          "size": 4500,
          "sha512": "8d600453d660c4a8bbe5732f72a2b3817405175fd76c4c77469a1bad8d0582402e0d38c400741db5b88d4be1547267dfa4bed6d873979de3cff6243e47b54ba0",
          "sha256": "c58e60b927d708415a94478332faf00007a91f083e4ce1d7ad1ad78b09769335",
          "sha1": "c96f6adbcf142611d78ca03c6ad21740cfb56ed7",
          "md5": "e47a12d385d0b3766b5703665880ed1f"
        }
      ]
    }
  ]
}
