{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmedia-bridge-ffmpeg/0.3.0/kmedia-bridge-ffmpeg-0.3.0.module",
    "group": "io.github.shusek",
    "module": "kmedia-bridge-ffmpeg",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.github.shusek",
          "module": "kmedia-bridge-api",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "ffmpeg.aar",
          "url": "kmedia-bridge-ffmpeg-android-0.3.0.aar",
          "size": 23684,
          "sha512": "3e1bf5cf1b14ee25b651094c708eab357c3f89274e8cd7e921455901dba5f599710457de4e7a17caae10b7c95f8439bf6031d54734d18cf25ed8822018bb9a25",
          "sha256": "6925b9ebbddb5b24284c06a2d654cb4987e4629dae773497544d04a77d79878b",
          "sha1": "faad714103ad78ccc638c078e5f3df91f2f1d3f1",
          "md5": "290946176a2acdfca7835e47a444c931"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.github.shusek",
          "module": "kmedia-bridge-api",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "ffmpeg.aar",
          "url": "kmedia-bridge-ffmpeg-android-0.3.0.aar",
          "size": 23684,
          "sha512": "3e1bf5cf1b14ee25b651094c708eab357c3f89274e8cd7e921455901dba5f599710457de4e7a17caae10b7c95f8439bf6031d54734d18cf25ed8822018bb9a25",
          "sha256": "6925b9ebbddb5b24284c06a2d654cb4987e4629dae773497544d04a77d79878b",
          "sha1": "faad714103ad78ccc638c078e5f3df91f2f1d3f1",
          "md5": "290946176a2acdfca7835e47a444c931"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ffmpeg-android-0.3.0-sources.jar",
          "url": "kmedia-bridge-ffmpeg-android-0.3.0-sources.jar",
          "size": 5301,
          "sha512": "237ec267cd1f1a6039f907612b2e0989edb48c5bae7c076a168d8cbc345f2047b9622f6e853f952ecafa07bed752bc1c39d6723357675cfe1872f391460861c0",
          "sha256": "1bae0208df500239df4222e7acc8942e4c3b6878535d3aac6c6bb8ca2cc0316e",
          "sha1": "b2cf6be78cff7e1d5c610a846ae1965860fd2264",
          "md5": "f48001ca2a124349bfe1c2504c86a63c"
        }
      ]
    }
  ]
}
