{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmedia-bridge-api/0.3.0/kmedia-bridge-api-0.3.0.module",
    "group": "io.github.shusek",
    "module": "kmedia-bridge-api",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-macosX64Main-0.3.0.klib",
          "url": "kmedia-bridge-api-macosx64-0.3.0.klib",
          "size": 51359,
          "sha512": "34b5ab4f952d935470ebaee43fa2a322167b9b4517d9e49db6cd5234553955741da2c22a4a98192c5865e7f741d0e1d5f6cc6c23b406322fea12fd1275da1ec3",
          "sha256": "75e6b1e58449b658cf926a5baf86642a7ac0dafe0266c283406c984ec72da9d6",
          "sha1": "e7b697729de0f7fbc5edc3ef57cec9d6f6de4ae1",
          "md5": "dc2608f202e2fc9676b80e5b7c548dea"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "api-macosx64-0.3.0-sources.jar",
          "url": "kmedia-bridge-api-macosx64-0.3.0-sources.jar",
          "size": 4500,
          "sha512": "8d600453d660c4a8bbe5732f72a2b3817405175fd76c4c77469a1bad8d0582402e0d38c400741db5b88d4be1547267dfa4bed6d873979de3cff6243e47b54ba0",
          "sha256": "c58e60b927d708415a94478332faf00007a91f083e4ce1d7ad1ad78b09769335",
          "sha1": "c96f6adbcf142611d78ca03c6ad21740cfb56ed7",
          "md5": "e47a12d385d0b3766b5703665880ed1f"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-macosx64-0.3.0-metadata.jar",
          "url": "kmedia-bridge-api-macosx64-0.3.0-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
