{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmedia-bridge-api/0.3.0/kmedia-bridge-api-0.3.0.module",
    "group": "io.github.shusek",
    "module": "kmedia-bridge-api",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-wasm-js-0.3.0.klib",
          "url": "kmedia-bridge-api-wasm-js-0.3.0.klib",
          "size": 60894,
          "sha512": "0ece99e6b7b0c8f7588eeabd8ccceab86c772c879e436ab22bec374e50610d5324182aac2f8bf1f372de1d7b9d230a43ef27f7b719183377bfbadd492354b280",
          "sha256": "6eaa41c0438711a4d86e0f7c941ac01f8040bb6ee2f7062c2064537f8cbc416a",
          "sha1": "04fa5bc4e7e7190acd4bcf29a20785b33e866e59",
          "md5": "6eb90a1682b68749073b47181f21e158"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-wasm-js-0.3.0.klib",
          "url": "kmedia-bridge-api-wasm-js-0.3.0.klib",
          "size": 60894,
          "sha512": "0ece99e6b7b0c8f7588eeabd8ccceab86c772c879e436ab22bec374e50610d5324182aac2f8bf1f372de1d7b9d230a43ef27f7b719183377bfbadd492354b280",
          "sha256": "6eaa41c0438711a4d86e0f7c941ac01f8040bb6ee2f7062c2064537f8cbc416a",
          "sha1": "04fa5bc4e7e7190acd4bcf29a20785b33e866e59",
          "md5": "6eb90a1682b68749073b47181f21e158"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "api-wasm-js-0.3.0-sources.jar",
          "url": "kmedia-bridge-api-wasm-js-0.3.0-sources.jar",
          "size": 4500,
          "sha512": "8d600453d660c4a8bbe5732f72a2b3817405175fd76c4c77469a1bad8d0582402e0d38c400741db5b88d4be1547267dfa4bed6d873979de3cff6243e47b54ba0",
          "sha256": "c58e60b927d708415a94478332faf00007a91f083e4ce1d7ad1ad78b09769335",
          "sha1": "c96f6adbcf142611d78ca03c6ad21740cfb56ed7",
          "md5": "e47a12d385d0b3766b5703665880ed1f"
        }
      ]
    }
  ]
}
