{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmedia-bridge-ffmpeg/0.3.0/kmedia-bridge-ffmpeg-0.3.0.module",
    "group": "io.github.shusek",
    "module": "kmedia-bridge-ffmpeg",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.github.shusek",
          "module": "kmedia-bridge-api",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "ffmpeg-linuxArm64Main-0.3.0.klib",
          "url": "kmedia-bridge-ffmpeg-linuxarm64-0.3.0.klib",
          "size": 26464,
          "sha512": "8c52bdca56a98c5c6679048b722cc3079ee3f2cb7778f75fb479f3a9231f8508afb4b054b9419f85db840b829f5e5894e94388139c8662d0606c521e98ef9274",
          "sha256": "593287210b0aef62777bdc67a9f19f4bf03ba90146af293f8c79ed4ef0693f97",
          "sha1": "a5a47340bc61ca6fde70e043f6be82d9e9dbc971",
          "md5": "f50cc56d2e40f891257f3bab446a3475"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ffmpeg-linuxarm64-0.3.0-sources.jar",
          "url": "kmedia-bridge-ffmpeg-linuxarm64-0.3.0-sources.jar",
          "size": 5301,
          "sha512": "237ec267cd1f1a6039f907612b2e0989edb48c5bae7c076a168d8cbc345f2047b9622f6e853f952ecafa07bed752bc1c39d6723357675cfe1872f391460861c0",
          "sha256": "1bae0208df500239df4222e7acc8942e4c3b6878535d3aac6c6bb8ca2cc0316e",
          "sha1": "b2cf6be78cff7e1d5c610a846ae1965860fd2264",
          "md5": "f48001ca2a124349bfe1c2504c86a63c"
        }
      ]
    }
  ]
}
