{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmedia-bridge-ffmpeg/0.1.0/kmedia-bridge-ffmpeg-0.1.0.module",
    "group": "io.github.shusek",
    "module": "kmedia-bridge-ffmpeg",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.github.shusek",
          "module": "kmedia-bridge-api",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "ffmpeg.aar",
          "url": "kmedia-bridge-ffmpeg-android-0.1.0.aar",
          "size": 19600,
          "sha512": "eb298bfadd918085165fe301e8aede11b044d25e34d4d8ec37a6cdd864b5dc0f8e6c0d7cdda7e139f8b839a73b5d3298398f3e1f1a55dfa8b8724c3b5711b609",
          "sha256": "e3b5470d9d936d8a400eb486effee3961ae888007450a6e40d3204f99c617d05",
          "sha1": "635e937555192368e188eb98e39478c60be46b16",
          "md5": "539453a0ed3b286517e5013ad341a362"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.github.shusek",
          "module": "kmedia-bridge-api",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "ffmpeg.aar",
          "url": "kmedia-bridge-ffmpeg-android-0.1.0.aar",
          "size": 19600,
          "sha512": "eb298bfadd918085165fe301e8aede11b044d25e34d4d8ec37a6cdd864b5dc0f8e6c0d7cdda7e139f8b839a73b5d3298398f3e1f1a55dfa8b8724c3b5711b609",
          "sha256": "e3b5470d9d936d8a400eb486effee3961ae888007450a6e40d3204f99c617d05",
          "sha1": "635e937555192368e188eb98e39478c60be46b16",
          "md5": "539453a0ed3b286517e5013ad341a362"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ffmpeg-android-0.1.0-sources.jar",
          "url": "kmedia-bridge-ffmpeg-android-0.1.0-sources.jar",
          "size": 4565,
          "sha512": "8511876b04ef7c0b298058fb9c805a19e9e982afb66836178caaf0b0e2ded2aa2d61274b4fba22eab23634cf78e859b25869c464a4efe4f1514178cc14a19601",
          "sha256": "4f8c2d18d6f27e16f57124b5056670819545d1340b7de31c9ad5f367ef33cf9d",
          "sha1": "8ae7ee13937f6d3519849b1b61aef0ae5c8eceed",
          "md5": "84b855ec3ae4794e9ecc9ea55a8df10b"
        }
      ]
    }
  ]
}
