{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmedia-bridge-api/0.1.0/kmedia-bridge-api-0.1.0.module",
    "group": "io.github.shusek",
    "module": "kmedia-bridge-api",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-linuxX64Main-0.1.0.klib",
          "url": "kmedia-bridge-api-linuxx64-0.1.0.klib",
          "size": 43119,
          "sha512": "c438cb13c4f5380229b5683805d2d7bcac79496c56f2518b5f69d8661cf9ef2be9fcfa1e210db9c41e938625570af56d062846d648e982c8c47803ee677cc8bd",
          "sha256": "d25d3e410dd7f7c5b502a85e3f76f9d779acc8ebd6cd6414b45980fdcd703b0c",
          "sha1": "9a06845c5d42e2c90f32eeb8a5bd69de24ab4853",
          "md5": "372ecc28acca161055298ba5ad0ec3f3"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "api-linuxx64-0.1.0-sources.jar",
          "url": "kmedia-bridge-api-linuxx64-0.1.0-sources.jar",
          "size": 3992,
          "sha512": "530501b265594bdc79ab3001505879f574b5f88d1251c56f51b529853419b27a8fcb0a9ba44ec72b3ade33a3f820e2f1ed18ad6c6e9bd0e2f5fdee8756f313e3",
          "sha256": "37dc5909d9cab42d9ee8ce058a29533fa32ad5f9afea2112e9a4b75f17d0cdd5",
          "sha1": "65c83861fc0928ff36db1f11daf43e3ef160c47a",
          "md5": "d812297bc13b5e1982cc2bfe5f739e12"
        }
      ]
    }
  ]
}
