{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmedia-bridge-api/0.1.0/kmedia-bridge-api-0.1.0.module",
    "group": "io.github.shusek",
    "module": "kmedia-bridge-api",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-jvm-0.1.0.jar",
          "url": "kmedia-bridge-api-jvm-0.1.0.jar",
          "size": 75175,
          "sha512": "f1c91c2efd2513d928473f37c9b34010947ce5c676734e446fe515177fbf4263abb16874b7e8f71d13e6e961fb4027dea084470986b802050bfc48acdcf086a4",
          "sha256": "806c5f7f21984957415d7be7af6b75427d599b820ede75c2fbed8787c8c696f7",
          "sha1": "8e46b8d21d06a60f218e4f7068c50ab25727e972",
          "md5": "82dbc2818ae16f8aba09c939d7b7685a"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-jvm-0.1.0.jar",
          "url": "kmedia-bridge-api-jvm-0.1.0.jar",
          "size": 75175,
          "sha512": "f1c91c2efd2513d928473f37c9b34010947ce5c676734e446fe515177fbf4263abb16874b7e8f71d13e6e961fb4027dea084470986b802050bfc48acdcf086a4",
          "sha256": "806c5f7f21984957415d7be7af6b75427d599b820ede75c2fbed8787c8c696f7",
          "sha1": "8e46b8d21d06a60f218e4f7068c50ab25727e972",
          "md5": "82dbc2818ae16f8aba09c939d7b7685a"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "api-jvm-0.1.0-sources.jar",
          "url": "kmedia-bridge-api-jvm-0.1.0-sources.jar",
          "size": 3992,
          "sha512": "530501b265594bdc79ab3001505879f574b5f88d1251c56f51b529853419b27a8fcb0a9ba44ec72b3ade33a3f820e2f1ed18ad6c6e9bd0e2f5fdee8756f313e3",
          "sha256": "37dc5909d9cab42d9ee8ce058a29533fa32ad5f9afea2112e9a4b75f17d0cdd5",
          "sha1": "65c83861fc0928ff36db1f11daf43e3ef160c47a",
          "md5": "d812297bc13b5e1982cc2bfe5f739e12"
        }
      ]
    }
  ]
}
