{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmedia-bridge-ffmpeg/0.2.0/kmedia-bridge-ffmpeg-0.2.0.module",
    "group": "io.github.shusek",
    "module": "kmedia-bridge-ffmpeg",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.github.shusek",
          "module": "kmedia-bridge-api",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "ffmpeg-linuxArm64Main-0.2.0.klib",
          "url": "kmedia-bridge-ffmpeg-linuxarm64-0.2.0.klib",
          "size": 24027,
          "sha512": "08ce4ccea859359ea6e1d7fb01ac64c92bccafb45ee1dadefe2e75afd7122e8f1851f12aa5186933853d0f0bc4e43df3f5e9a7e20c587cbd3e8247ea947acf38",
          "sha256": "bdd517223bfb63f61d28df8f9d9775b6d666b485de86ac733a3cce3a6706dc7d",
          "sha1": "01476095dbdd48da6664fc2b33e0bf8cc6a3336f",
          "md5": "96ca92170197f234b14476c402ed801a"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ffmpeg-linuxarm64-0.2.0-sources.jar",
          "url": "kmedia-bridge-ffmpeg-linuxarm64-0.2.0-sources.jar",
          "size": 4565,
          "sha512": "8511876b04ef7c0b298058fb9c805a19e9e982afb66836178caaf0b0e2ded2aa2d61274b4fba22eab23634cf78e859b25869c464a4efe4f1514178cc14a19601",
          "sha256": "4f8c2d18d6f27e16f57124b5056670819545d1340b7de31c9ad5f367ef33cf9d",
          "sha1": "8ae7ee13937f6d3519849b1b61aef0ae5c8eceed",
          "md5": "84b855ec3ae4794e9ecc9ea55a8df10b"
        }
      ]
    }
  ]
}
