{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmedia-bridge-api/0.3.0/kmedia-bridge-api-0.3.0.module",
    "group": "io.github.shusek",
    "module": "kmedia-bridge-api",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-mingwX64Main-0.3.0.klib",
          "url": "kmedia-bridge-api-mingwx64-0.3.0.klib",
          "size": 51360,
          "sha512": "32be84edd84c94512c349c51eea5d1fc74634bed5ec1496c7d9c74a910f77d50a5547945b7e721d62dc6e5b86f7aa608aa84033dbd7152a24915758baf60ffc3",
          "sha256": "66e2645a4e5bcf03e6a58cc09bdee6c9f8e6357f0bfbd009ab74bbee78c60907",
          "sha1": "00fcf8fd2c78406ad65c9592136c50c0db409b52",
          "md5": "66c1a7c8d38ae21e32b1483c33ab6633"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "api-mingwx64-0.3.0-sources.jar",
          "url": "kmedia-bridge-api-mingwx64-0.3.0-sources.jar",
          "size": 4500,
          "sha512": "8d600453d660c4a8bbe5732f72a2b3817405175fd76c4c77469a1bad8d0582402e0d38c400741db5b88d4be1547267dfa4bed6d873979de3cff6243e47b54ba0",
          "sha256": "c58e60b927d708415a94478332faf00007a91f083e4ce1d7ad1ad78b09769335",
          "sha1": "c96f6adbcf142611d78ca03c6ad21740cfb56ed7",
          "md5": "e47a12d385d0b3766b5703665880ed1f"
        }
      ]
    }
  ]
}
