{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmedia-bridge-ffmpeg/0.2.0/kmedia-bridge-ffmpeg-0.2.0.module",
    "group": "io.github.shusek",
    "module": "kmedia-bridge-ffmpeg",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "io.github.shusek",
          "module": "kmedia-bridge-api",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "ffmpeg-wasm-js-0.2.0.klib",
          "url": "kmedia-bridge-ffmpeg-wasm-js-0.2.0.klib",
          "size": 34423,
          "sha512": "aa9e152eb6abf1ff95ea07d955c2e92d3b521baf2007d367df762731ee7d06c7eb04093f8fe5c1d33ee1cd392ff45c952cd687960df9f07e395626aacc09a1e4",
          "sha256": "d530ba5ca2e801e805f24ad2ab2a767620302e5db8929e878998c898bf70a068",
          "sha1": "e3fc14380eaa76bc460418e3a7c84598fd35555c",
          "md5": "8360c24774d07340d2f99cc31155f42b"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "io.github.shusek",
          "module": "kmedia-bridge-api",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "ffmpeg-wasm-js-0.2.0.klib",
          "url": "kmedia-bridge-ffmpeg-wasm-js-0.2.0.klib",
          "size": 34423,
          "sha512": "aa9e152eb6abf1ff95ea07d955c2e92d3b521baf2007d367df762731ee7d06c7eb04093f8fe5c1d33ee1cd392ff45c952cd687960df9f07e395626aacc09a1e4",
          "sha256": "d530ba5ca2e801e805f24ad2ab2a767620302e5db8929e878998c898bf70a068",
          "sha1": "e3fc14380eaa76bc460418e3a7c84598fd35555c",
          "md5": "8360c24774d07340d2f99cc31155f42b"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "ffmpeg-wasm-js-0.2.0-sources.jar",
          "url": "kmedia-bridge-ffmpeg-wasm-js-0.2.0-sources.jar",
          "size": 4565,
          "sha512": "8511876b04ef7c0b298058fb9c805a19e9e982afb66836178caaf0b0e2ded2aa2d61274b4fba22eab23634cf78e859b25869c464a4efe4f1514178cc14a19601",
          "sha256": "4f8c2d18d6f27e16f57124b5056670819545d1340b7de31c9ad5f367ef33cf9d",
          "sha1": "8ae7ee13937f6d3519849b1b61aef0ae5c8eceed",
          "md5": "84b855ec3ae4794e9ecc9ea55a8df10b"
        }
      ]
    }
  ]
}
